name: Teste

on:
  push:
    branches: [ main ]

jobs:

  test:
    name: Teste
    runs-on: ubuntu-latest
      
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        working-directory: api
        run: |
          pip install -r requirements.txt
          